[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 2

[tool.mypy]
disallow_untyped_calls = true
mypy_path = "stubs"

[tool.pylint.FORMAT]
max-line-length = 120
extension-pkg-allow-list = "pikepdf._core"